import { mkdtemp, readFile, rm, cp } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Command } from 'commander';
import { describe, expect, it } from 'vitest';

import { StaticAnalyzer } from '../src/analyzer/index.js';
import { DocumentGenerator } from '../src/generator/index.js';
import { handleGenerate } from '../src/commands/generate.js';

const fixturesRoot = path.resolve('test/fixtures');

async function createTempWorkspace(sourceFixture: string): Promise<string> {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), 'codeatlas-'));
  await cp(path.join(fixturesRoot, sourceFixture), tempRoot, { recursive: true });
  return tempRoot;
}

describe('DocumentGenerator', () => {
  it('writes the six atlas documents with markdown metadata', async () => {
    const workspace = await createTempWorkspace('fullstack-mixed');
    const outputDirectory = path.join(workspace, 'docs', 'atlas');

    try {
      const analysis = await new StaticAnalyzer(workspace).analyze();
      const generator = new DocumentGenerator(analysis, outputDirectory);
      const result = await generator.generate('merge');

      expect(result.generatedFiles).toHaveLength(6);
      expect(await readFile(path.join(outputDirectory, 'architecture.md'), 'utf8')).toContain('# Architecture');
      expect(await readFile(path.join(outputDirectory, 'architecture.md'), 'utf8')).toContain('Generated by CodeAtlas');
      expect(await readFile(path.join(outputDirectory, 'entry_points.md'), 'utf8')).toContain('node dist/server.js');
      expect(await readFile(path.join(outputDirectory, 'dependencies.md'), 'utf8')).toContain('Core');
      expect(await readFile(path.join(outputDirectory, 'api.md'), 'utf8')).toContain('Routes by Resource');
      expect(await readFile(path.join(outputDirectory, 'atlas_summary.md'), 'utf8')).toContain('This is a fullstack project');
    } finally {
      await rm(workspace, { recursive: true, force: true });
    }
  });
});

describe('generate command', () => {
  it('runs the analyzer and generator for the current workspace', async () => {
    const workspace = await createTempWorkspace('python-backend');
    const previousCwd = process.cwd();

    try {
      process.chdir(workspace);
      await handleGenerate.call(new Command(), {});

      const generatedArchitecture = await readFile(path.join(workspace, 'docs', 'atlas', 'architecture.md'), 'utf8');
      expect(generatedArchitecture).toContain('# Architecture');
      expect(generatedArchitecture).not.toContain('fullstack');
      expect(generatedArchitecture).toContain('backend');
    } finally {
      process.chdir(previousCwd);
      await rm(workspace, { recursive: true, force: true });
    }
  });
});
