import { promises as fs } from 'node:fs';
import path from 'node:path';
import cliProgress from 'cli-progress';

import type { AnalysisResult, ApiRouteItem, DependencyItem, EntryPointItem, FolderStructureItem } from '../analyzer/index.js';
import { ensureDirectory, writeTextFile } from '../utils/fs.js';

export interface GeneratedDocument {
  fileName: string;
  content: string;
}

export interface GenerateDocumentsResult {
  outputDirectory: string;
  generatedFiles: string[];
}

const CODEATLAS_BADGE = 'Generated by CodeAtlas';
const DEFAULT_TIMESTAMP_FORMAT = new Intl.DateTimeFormat('en-US', {
  dateStyle: 'medium',
  timeStyle: 'medium'
});

const RISKY_PACKAGES = new Set([
  'serialize-javascript',
  'eval',
  'lodash',
  'event-stream',
  'vm2',
  'node-serialize',
  'handlebars',
  'ejs',
  'nunjucks',
  'minimist'
]);

const CATEGORY_GROUPS: Record<string, string> = {
  ui: 'Core',
  validation: 'Core',
  'http-client': 'Core',
  'state-management': 'Core',
  utility: 'Core',
  orm: 'Database',
  auth: 'Auth',
  testing: 'Testing',
  devtool: 'DevTools',
  ai: 'AI/ML'
};

export class DocumentGenerator {
  constructor(
    private readonly analysis: AnalysisResult,
    private readonly outputDirectory: string = path.resolve(process.cwd(), 'docs', 'atlas')
  ) {}

  async generate(overwriteMode: 'overwrite' | 'merge' = 'merge'): Promise<GenerateDocumentsResult> {
    await ensureDirectory(this.outputDirectory);
    if (overwriteMode === 'overwrite') {
      await clearDirectoryContents(this.outputDirectory);
    }

    const documents = this.buildDocuments();
    const generatedFiles: string[] = [];
    const progressBar = new cliProgress.SingleBar(
      {
        format: 'Writing atlas |{bar}| {value}/{total} files',
        hideCursor: true,
        clearOnComplete: false
      },
      cliProgress.Presets.shades_classic
    );

    progressBar.start(documents.length, 0);
    try {
      for (const document of documents) {
        await writeTextFile(path.join(this.outputDirectory, document.fileName), document.content);
        generatedFiles.push(document.fileName);
        progressBar.increment();
      }
    } finally {
      progressBar.stop();
    }

    return {
      outputDirectory: this.outputDirectory,
      generatedFiles
    };
  }

  buildDocuments(): GeneratedDocument[] {
    return [
      {
        fileName: 'architecture.md',
        content: this.buildArchitectureDocument()
      },
      {
        fileName: 'folder_structure.md',
        content: this.buildFolderStructureDocument()
      },
      {
        fileName: 'entry_points.md',
        content: this.buildEntryPointsDocument()
      },
      {
        fileName: 'dependencies.md',
        content: this.buildDependenciesDocument()
      },
      {
        fileName: 'api.md',
        content: this.buildApiDocument()
      },
      {
        fileName: 'atlas_summary.md',
        content: this.buildSummaryDocument()
      }
    ];
  }

  private buildArchitectureDocument(): string {
    const techRows = this.flattenTechStack();
    const detectedPatterns = this.detectPatterns();
    const deploymentSummary = this.buildDeploymentSummary();

    return renderDocument(
      'Architecture',
      [
        '## Project Snapshot',
        `- Project type: ${escapeMarkdown(this.analysis.projectType)}`,
        `- Language profile: ${escapeMarkdown(this.analysis.language)}`,
        `- API endpoints detected: ${this.analysis.apiRoutes.length}`,
        '',
        '## Detected Tech Stack',
        buildTable(['Layer', 'Technology', 'Purpose'], techRows.map((row) => [row.layer, row.technology, row.purpose])),
        '',
        '## Detected Patterns',
        detectedPatterns.length > 0
          ? detectedPatterns.map((pattern) => `- ${escapeMarkdown(pattern)}`).join('\n')
          : '- No strong architectural pattern was detected from the available signals.',
        '',
        '## Deployment and Infrastructure',
        deploymentSummary
      ].join('\n'));
  }

  private buildFolderStructureDocument(): string {
    const importantFolders = this.getImportantFolders();
    const tree = renderFolderTree(this.analysis.folderStructure);

    return renderDocument(
      'Folder Structure',
      [
        '## Most Important Folders',
        importantFolders.length > 0
          ? importantFolders.map((folder) => `- ${escapeMarkdown(folder.path)} - ${escapeMarkdown(folder.purpose)}`).join('\n')
          : '- No folders were detected.',
        '',
        '## Annotated Tree',
        '```text',
        tree,
        '```'
      ].join('\n'));
  }

  private buildEntryPointsDocument(): string {
    const startupCommands = this.getStartupCommands();
    const rows = this.analysis.entryPoints.map((entryPoint) => [
      entryPoint.file,
      entryPoint.type,
      describeEntryPoint(entryPoint)
    ]);

    return renderDocument(
      'Entry Points',
      [
        '## Detected Entry Points',
        buildTable(['File', 'Type', 'What it does'], rows),
        '',
        '## Startup Commands',
        startupCommands.length > 0
          ? startupCommands.map((command) => `- ${escapeMarkdown(command)}`).join('\n')
          : '- No startup command was detected.'
      ].join('\n'));
  }

  private buildDependenciesDocument(): string {
    const grouped = this.groupDependencies();
    const sections = Object.entries(grouped).map(([group, dependencies]) => {
      const rows = dependencies.map((dependency) => [
        dependency.name,
        dependency.version,
        dependency.category,
        riskAwareDescription(dependency)
      ]);
      return [
        `### ${group}`,
        dependencies.length > 0 ? buildTable(['Package', 'Version', 'Category', 'What it does'], rows) : '_None detected._'
      ].join('\n\n');
    });

    const risky = this.analysis.dependencies.filter((dependency) => isRiskyDependency(dependency.name));

    return renderDocument(
      'Dependencies',
      [
        '## Grouped Dependencies',
        sections.join('\n\n'),
        '',
        '## Security Risk Flags',
        risky.length > 0
          ? risky.map((dependency) => `- ⚠ ${escapeMarkdown(dependency.name)} is on the basic risk watchlist.`).join('\n')
          : '- No packages matched the basic risk watchlist.'
      ].join('\n'));
  }

  private buildApiDocument(): string {
    const grouped = groupRoutesByResource(this.analysis.apiRoutes);
    const sections = Object.entries(grouped).map(([resource, routes]) => {
      const rows = routes.map((route) => [route.method, route.path, route.file, describeRoute(route)]);
      const protectionState = routes.some((route) => isProtectedRoute(route)) ? 'Protected routes detected in this group.' : 'No clear protection middleware was detected.';
      return [
        `### ${resource}`,
        buildTable(['Method', 'Route', 'File', 'Description'], rows),
        '',
        `- ${escapeMarkdown(protectionState)}`
      ].join('\n\n');
    });

    return renderDocument(
      'API Routes',
      [
        '## Routes by Resource',
        sections.length > 0 ? sections.join('\n\n') : '_No API routes detected._'
      ].join('\n'));
  }

  private buildSummaryDocument(): string {
    const techStackSummary = this.buildTechStackSummary();
    const mainFiles = this.getFilesToReadFirst();
    const runCommands = this.getStartupCommands();
    const database = this.analysis.techStack.database[0] ?? 'unknown';
    const auth = this.analysis.techStack.auth[0] ?? 'none detected';

    return renderDocument(
      'Atlas Summary',
      [
        `This is a ${escapeMarkdown(this.analysis.projectType)} project built with ${escapeMarkdown(techStackSummary)}.`,
        `It has ${this.analysis.apiRoutes.length} API endpoints, uses ${escapeMarkdown(database)} for storage, and authenticates with ${escapeMarkdown(auth)}.`,
        '',
        '## 5 Files to Read First',
        mainFiles.length > 0 ? mainFiles.map((file) => `- ${escapeMarkdown(file)}`).join('\n') : '- No priority files could be inferred.',
        '',
        '## How to Run',
        runCommands.length > 0 ? runCommands.map((command: string) => `- ${escapeMarkdown(command)}`).join('\n') : '- No startup command was detected.'
      ].join('\n'));
  }

  private flattenTechStack(): Array<{ layer: string; technology: string; purpose: string }> {
    return [
      ...this.analysis.techStack.frontend.map((technology) => ({ layer: 'Frontend', technology, purpose: 'User interface layer' })),
      ...this.analysis.techStack.backend.map((technology) => ({ layer: 'Backend', technology, purpose: 'Server-side application layer' })),
      ...this.analysis.techStack.database.map((technology) => ({ layer: 'Database', technology, purpose: 'Data storage and ORM layer' })),
      ...this.analysis.techStack.auth.map((technology) => ({ layer: 'Auth', technology, purpose: 'Authentication and authorization' })),
      ...this.analysis.techStack.deployment.map((technology) => ({ layer: 'Deployment', technology, purpose: 'Infrastructure and delivery' })),
      ...this.analysis.techStack.ai.map((technology) => ({ layer: 'AI/ML', technology, purpose: 'Machine learning and AI integration' }))
    ];
  }

  private detectPatterns(): string[] {
    const patterns = new Set<string>();
    const folderNames = this.analysis.folderStructure.map((folder) => folder.path.toLowerCase());

    if (this.analysis.apiRoutes.length > 0) {
      patterns.add('REST API surface');
    }
    if (folderNames.some((folder) => folder.includes('models')) && folderNames.some((folder) => folder.includes('services'))) {
      patterns.add('MVC-style layering');
    }
    if (folderNames.some((folder) => folder.includes('components')) && folderNames.some((folder) => folder.includes('pages'))) {
      patterns.add('UI component architecture');
    }
    if (this.analysis.techStack.frontend.length > 0 && this.analysis.techStack.backend.length > 0) {
      patterns.add('Fullstack application');
    }
    if (this.analysis.techStack.deployment.includes('docker') || this.analysis.techStack.deployment.includes('docker-compose')) {
      patterns.add('Containerized deployment');
    }
    if (folderNames.some((folder) => folder.includes('packages')) || folderNames.some((folder) => folder.includes('apps'))) {
      patterns.add('Monorepo layout');
    }
    if (this.analysis.techStack.backend.length > 1) {
      patterns.add('Service-oriented backend split');
    }

    return [...patterns];
  }

  private buildDeploymentSummary(): string {
    const parts: string[] = [];
    if (this.analysis.techStack.deployment.length > 0) {
      parts.push(`Deployment signals: ${this.analysis.techStack.deployment.map(escapeMarkdown).join(', ')}`);
    }

    const commands = this.getStartupCommands();
    if (commands.length > 0) {
      parts.push(`Detected startup commands: ${commands.map(escapeMarkdown).join('; ')}`);
    }

    if (parts.length === 0) {
      return '- No deployment or infrastructure signals were detected.';
    }

    return parts.map((part) => `- ${part}`).join('\n');
  }

  private getImportantFolders(): FolderStructureItem[] {
    const folderPriority = (folder: FolderStructureItem): number => {
      const lower = folder.path.toLowerCase();
      if (lower === 'src') return 0;
      if (lower.startsWith('src/')) return 1;
      if (lower.includes('app') || lower.includes('api')) return 2;
      if (lower.includes('components') || lower.includes('services') || lower.includes('models')) return 3;
      return 4;
    };

    return [...this.analysis.folderStructure]
      .sort((left, right) => folderPriority(left) - folderPriority(right) || left.depth - right.depth || left.path.localeCompare(right.path))
      .slice(0, 5);
  }

  private getStartupCommands(): string[] {
    const commands = new Set<string>();
    for (const entryPoint of this.analysis.entryPoints) {
      if (entryPoint.type.startsWith('start-script:') && entryPoint.command) {
        commands.add(entryPoint.command);
      }
      if (entryPoint.type === 'docker-entry-point' && entryPoint.command) {
        commands.add(`Dockerfile ${entryPoint.command}`);
      }
    }

    return [...commands];
  }

  private getFilesToReadFirst(): string[] {
    const files = new Set<string>();
    for (const entryPoint of this.analysis.entryPoints) {
      files.add(entryPoint.file.replace(/^package\.json -> /, 'package.json'));
    }
    for (const route of this.analysis.apiRoutes.slice(0, 3)) {
      files.add(route.file);
    }
    for (const folder of this.getImportantFolders()) {
      if (folder.path.includes('src')) {
        files.add(`${folder.path}/index.ts`);
      }
    }

    return [...files].slice(0, 5);
  }

  private buildTechStackSummary(): string {
    const stack = [
      ...this.analysis.techStack.frontend,
      ...this.analysis.techStack.backend,
      ...this.analysis.techStack.database,
      ...this.analysis.techStack.auth,
      ...this.analysis.techStack.ai
    ];

    if (stack.length === 0) {
      return 'an unidentified stack';
    }

    return stack.map(escapeMarkdown).join(', ');
  }

  private groupDependencies(): Record<string, DependencyItem[]> {
    const grouped: Record<string, DependencyItem[]> = {
      Core: [],
      Database: [],
      Auth: [],
      Testing: [],
      DevTools: [],
      'AI/ML': []
    };

    for (const dependency of this.analysis.dependencies) {
      const group = CATEGORY_GROUPS[dependency.category] ?? 'Core';
      const bucket = grouped[group] ?? (grouped[group] = []);
      bucket.push(dependency);
    }

    for (const dependencyList of Object.values(grouped)) {
      dependencyList.sort((left, right) => left.name.localeCompare(right.name));
    }

    return grouped;
  }
}

function renderDocument(title: string, body: string): string {
  const timestamp = DEFAULT_TIMESTAMP_FORMAT.format(new Date());
  return [
    `# ${escapeMarkdown(title)}`,
    '',
    `Generated: ${escapeMarkdown(timestamp)}`,
    '',
    body,
    '',
    '---',
    CODEATLAS_BADGE
  ].join('\n');
}

function buildTable(headers: string[], rows: string[][]): string {
  const normalizedRows = rows.length > 0 ? rows : [headers.map(() => '_None_')];
  const headerRow = `| ${headers.map(escapeMarkdown).join(' | ')} |`;
  const dividerRow = `| ${headers.map(() => '---').join(' | ')} |`;
  const bodyRows = normalizedRows.map((row) => `| ${row.map(escapeMarkdown).join(' | ')} |`);
  return [headerRow, dividerRow, ...bodyRows].join('\n');
}

function escapeMarkdown(value: string): string {
  let escaped = value.replaceAll('\\', '\\\\');
  for (const character of ['`', '|', '*', '_', '{', '}', '[', ']', '#', '+', '-', '!']) {
    escaped = escaped.replaceAll(character, `\\${character}`);
  }
  return escaped.replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function renderFolderTree(folderStructure: FolderStructureItem[]): string {
  const root = buildTree(folderStructure);
  const lines: string[] = [];

  const renderNode = (node: TreeNode, prefix: string, isLast: boolean): void => {
    const connector = prefix.length === 0 ? '' : isLast ? '`-- ' : '|-- ';
    const line = `${prefix}${connector}${node.name}/ - ${node.purpose}`;
    lines.push(line);

    const childPrefix = prefix.length === 0 ? '' : `${prefix}${isLast ? '    ' : '|   '}`;
    node.children.forEach((child, index) => renderNode(child, childPrefix, index === node.children.length - 1));
  };

  root.children.forEach((child, index) => renderNode(child, '', index === root.children.length - 1));
  return lines.join('\n');
}

interface TreeNode {
  name: string;
  purpose: string;
  children: TreeNode[];
}

function buildTree(folderStructure: FolderStructureItem[]): TreeNode {
  const root: TreeNode = { name: '.', purpose: 'Project root', children: [] };

  for (const folder of folderStructure) {
    const segments = folder.path.split('/');
    let current = root;
    let accumulated = '';
    for (const segment of segments) {
      accumulated = accumulated ? `${accumulated}/${segment}` : segment;
      let child = current.children.find((entry) => entry.name === segment);
      if (!child) {
        const purpose = folder.path === accumulated ? folder.purpose : inferFolderPurpose(segment);
        child = { name: segment, purpose, children: [] };
        current.children.push(child);
      }
      current = child;
    }
  }

  sortTree(root);
  return root;
}

function sortTree(node: TreeNode): void {
  node.children.sort((left, right) => left.name.localeCompare(right.name));
  node.children.forEach((child) => sortTree(child));
}

function inferFolderPurpose(folderName: string): string {
  const lowered = folderName.toLowerCase();
  if (lowered === 'api' || lowered === 'routes') return 'API routes';
  if (lowered === 'components') return 'UI components';
  if (lowered === 'services') return 'Business logic';
  if (lowered === 'models') return 'Data models';
  if (lowered === 'utils') return 'Utilities';
  if (lowered === 'middleware') return 'Middleware';
  if (lowered === 'pages') return 'Page routes';
  if (lowered === 'app') return 'Application code';
  if (lowered === 'lib') return 'Shared library';
  return 'Project structure';
}

function describeEntryPoint(entryPoint: EntryPointItem): string {
  const file = path.basename(entryPoint.file);
  if (entryPoint.type.startsWith('start-script:')) {
    return `Starts the application via ${entryPoint.command ?? 'the package.json start script'}.`;
  }
  if (entryPoint.type === 'docker-entry-point') {
    return entryPoint.command ? `Container startup command: ${entryPoint.command}.` : 'Defines the container startup for the application.';
  }
  if (entryPoint.type === 'bin-entry-point') {
    return 'Exposes the CLI binary entry point.';
  }
  if (file === 'server.ts' || file === 'app.ts') {
    return 'Starts the HTTP server.';
  }
  if (file === 'main.ts' || file === 'index.ts') {
    return 'Acts as the main runtime entry point.';
  }
  if (file === 'app.py' || file === 'main.py') {
    return 'Starts the Python application server.';
  }
  return 'Acts as a project entry point.';
}

function describeRoute(route: ApiRouteItem): string {
  const resource = inferResource(route.path);
  const location = route.file.toLowerCase();
  if (location.includes('middleware') || location.includes('guard') || location.includes('auth')) {
    return `Likely protected ${resource} route.`;
  }
  if (/\/admin|\/secure|\/private|\/internal/i.test(route.path)) {
    return `Likely protected ${resource} route.`;
  }
  return `Handles ${resource} requests.`;
}

function groupRoutesByResource(routes: ApiRouteItem[]): Record<string, ApiRouteItem[]> {
  const grouped: Record<string, ApiRouteItem[]> = {};
  for (const route of routes) {
    const resource = inferResource(route.path);
    const bucket = grouped[resource] ?? (grouped[resource] = []);
    bucket.push(route);
  }

  for (const routeGroup of Object.values(grouped)) {
    routeGroup.sort((left, right) => left.path.localeCompare(right.path) || left.method.localeCompare(right.method));
  }

  return grouped;
}

function inferResource(routePath: string): string {
  const cleaned = routePath.replace(/^\//, '').replace(/[:?].*$/, '');
  const segment = cleaned.split('/')[0] ?? 'root';
  return segment || 'root';
}

function isProtectedRoute(route: ApiRouteItem): boolean {
  return /auth|guard|middleware|admin|private|secure|internal/i.test(`${route.file} ${route.path}`);
}

function isRiskyDependency(name: string): boolean {
  return RISKY_PACKAGES.has(name.toLowerCase());
}

function riskAwareDescription(dependency: DependencyItem): string {
  const flag = isRiskyDependency(dependency.name) ? ' ⚠ possible security risk' : '';
  return `${dependency.description}${flag}`;
}

async function clearDirectoryContents(directoryPath: string): Promise<void> {
  const entries = await fs.readdir(directoryPath, { withFileTypes: true });
  await Promise.all(
    entries.map(async (entry) => {
      await fs.rm(path.join(directoryPath, entry.name), { recursive: true, force: true });
    })
  );
}
